
#Jer Integration override options
[jer-integration]
	#Enable / Disable patch for Randomite Classic
	randomite = false
	#Enable / Disable patch for Create
	create = false
	#Enable / Disable patch for Immersive Engineering
	immersiveengineering = false
	#Enable / Disable patch for Tinkers' Construct
	tconstruct = false
	#Enable / Disable patch for Mekanism
	mekanism = false

